# Copyright 2024 Canonical Ltd.
# See LICENSE file for licensing details.
[tox]
requires =
	tox>=4
env_list = lint, fmt, unit, cover

[testenv]
setenv =
	name=data-platform-k8s-mutator
	registry_namespace=ghcr.io/canonical
	repo=https://github.com/canonical/data-platform-k8s-mutator

[testenv:lint]
description = run linters
skip_install = true
setenv =
	RUFF_CACHE_DIR = {envtmpdir}/ruff_cache
deps =
	yamllint
	ruff
commands = 
	yamllint --no-warnings rockcraft.yaml
	ruff check --extend-ignore=D,E501 app.py scripts/
	ruff format --check app.py scripts/

[testenv:fmt]
description = auto-fix and format
skip_install = true
setenv =
	RUFF_CACHE_DIR = {envtmpdir}/ruff_cache
deps =
	ruff
commands =
	ruff check --fix --extend-ignore=D,E501 app.py scripts/
	ruff format app.py scripts/

[testenv:unit]
description = run unit tests
skip_install = true
setenv =
	PYTHONPATH = {tox_root}
deps =
	uv
commands =
	uv sync --extra dev
	uv run pytest tests/ -v --rootdir={tox_root} {posargs}

[testenv:cover]
description = run unit tests with coverage report
skip_install = true
setenv =
	PYTHONPATH = {tox_root}
deps =
	uv
commands =
	uv sync --extra dev
	uv run pytest tests/ -v --rootdir={tox_root} --cov=app --cov-report=term-missing --cov-report=html {posargs}
