# Copyright 2024 Canonical Ltd.
# See LICENSE file for licensing details.
[tox]
requires =
	tox>=4
env_list = lint, fmt, integration

[testenv]
setenv =
	name=data-platform-k8s-mutator
	registry_namespace=ghcr.io/canonical
	repo=https://github.com/canonical/data-platform-k8s-mutator

[testenv:lint]
description = run linters
skip_install = true
setenv =
	RUFF_CACHE_DIR = {envtmpdir}/ruff_cache
deps =
	yamllint
	ruff
commands = 
	yamllint --no-warnings rockcraft.yaml
	ruff check --extend-ignore=D,E501 app.py
	ruff format --check app.py

[testenv:fmt]
description = auto-fix and format
skip_install = true
setenv =
	RUFF_CACHE_DIR = {envtmpdir}/ruff_cache
deps =
	ruff
commands =
	ruff check --fix --extend-ignore=D,E501 app.py
	ruff format app.py
