name: Lint and test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  lint:
    runs-on: [self-hosted, linux, X64, jammy, large]
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install tox
        run: python3 -m pip install tox
      - name: Format (ruff)
        run: tox -e fmt
      - name: Verify formatting
        run: git diff --exit-code
      - name: Lint
        run: tox -e lint

  test:
    runs-on: [self-hosted, linux, X64, jammy, large]
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install tox
        run: python3 -m pip install tox
      - name: Unit tests
        run: tox -e unit
